lib/gladman-fcrypt/aescrypt.c

The word `unused` interferes with gcc macros like `__attribute__((unused))`.

Don't use `unused` in aescrypt macro

---

libzip.pc.in

pkg-config: Use Libs.private for link dependencies

---

CMakeLists.txt

This patch adds 4 options to allow custom build of libzip.
```
OPTION(BUILD_TOOLS "Build tools in the src directory (zipcmp, zipmerge, ziptool)" ON)
OPTION(BUILD_REGRESS "Build regression tests" ON)
OPTION(BUILD_EXAMPLES "Build examples" ON)
OPTION(BUILD_DOC "Build documentation" ON)
```
This allow easier integration in projects when all is not needed (or would be impossible to build ex: android NDK).

adding customization for build

---

man/zip_source_stat.mdoc

That, or point to the zip_stat page directly :)

doc: typo: ZIP_SOURCE_STAT_* -> ZIP_STAT_*

---

regress/tryopen.c

format functions expect a constant expression, not a variable.

tryopen: Fix -Wformat=2 warning

---

examples/in-memory.c
regress/add_from_filep.c
regress/ziptool_regress.c
src/zipcmp.c

Some commercial systems have wrong notion about opening files in
non-binary mode, pre-emptively open all the files as binary.

Ensure all calls `fopen` use "rb" mode

---

lib/zip_source_filep.c

The function is not used on this platform and tries to call out to
`_zip_mkstempm` not defined on this platform. See discussion in
https://github.com/nih-at/libzip/commit/2bba8fcea39c446d77e4671d550931417d9a4fbf#r37699033

Prevent compilation of `create_temp_output` on Windows

---

.github/workflows/main.yml

[CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) will run the fuzz target (`zip_read_fuzzer.c`) each time a pull request is submitted to detect bugs before they make it into the codebase.
It runs for about 10 minutes and produces a test case if it finds a bug, the bug can be reproduced with [fuzz_main](https://github.com/nih-at/libzip/blob/master/regress/CMakeLists.txt#L221) if the project is built with `-fsanitize=address/undefined` set as CFLAGS.

CIFuzz integration

---

lib/zip_stat_index.c

This was found on a project we have running on Windows. We would get a native crash when opening and updating an entry from a stream. We found that in this case `entry->changes` was `NULL` which was causing the crash. 
Not sure if this is right but adding the `NULL` check works around the problem. It might be enough, if not please let me know what else needs to happen. I'm quite happy to add code to this PR.

Add missing NULL check in zip_stat_index.

---

CMakeLists.txt

One export() was not skipped when installation is disabled.
https://github.com/nih-at/libzip/issues/180

fix conditional cmake install/export

---

lib/zip_source_file_win32.c

`ENOENT` means no such file or directory, which on Windows is either
`FILE_NOT_FOUND` or `PATH_NOT_FOUND`.  I've noticed the meaningless
"Unknown error" while working on <https://bugs.php.net/80261>, where
the overlong path caused `GetFileAttributesExW()` to fail with
`PATH_NOT_FOUND`.

[Windows] Provide meaningful error message for PATH_NOT_FOUND

---

lib/zip_source_file_win32.h

Without this (and if not the ZIP_ALLOCATE_BUFFER define is set by chance), you will get on Windows 64-bit (at least if only zlib/zstd ist compiled in):
D:\makefactory\zip-ZMWGK7ie\zip\src\lib\zip_source_file_win32_utf16.c(81): warning C4013: 'malloc' undefined; assuming extern returning int
D:\makefactory\zip-ZMWGK7ie\zip\src\lib\zip_source_file_win32_utf16.c(81): warning C4312: 'type cast': conversion from 'int' to 'char *' of greater size
D:\makefactory\zip-ZMWGK7ie\zip\src\lib\zip_source_file_win32_utf8.c(63): warning C4013: 'malloc' undefined; assuming extern returning int
D:\makefactory\zip-ZMWGK7ie\zip\src\lib\zip_source_file_win32_utf8.c(63): warning C4312: 'type cast': conversion from 'int' to 'wchar_t *' of greater size
D:\makefactory\zip-ZMWGK7ie\zip\src\lib\zip_source_file_win32 …

add missing header to have malloc/free available

---

lib/zip_crypto_win.c

Additionally I also had to add the <limits.h> include for INT_MAX and ULONG_MAX.

Move variable declaration to support old compiler

---

CMakeLists.txt

In c39f01daa6ce011960e852bfc6147a96769b0955
> ZSTD_minCLevel() and ZSTD_maxCLevel() are from zstd 1.5 
From https://github.com/facebook/zstd/commit/9bb6c15f7966f59d001f782f087484a414eba570
The commit which introduces this function is in 1.3.6
Notice: and, at least, I can confirm libzip 1.8.0 work as expected (build + test suite) on RHEL / CentOS 8 which have 1.4.4

Zstd 1.3.6 is enough

---

lib/zip_source_file_stdio_named.c

In `_zip_stdio_op_create_temp_output_cloning` when `fseeko` fails the `temp` value gets freed but then the freed pointer is assigned to `ctx->tmpname`.

Use after free when fseeko fails

---

lib/zip_source_file_win32.c

Commit (https://github.com/nih-at/libzip/commit/528ab2d6f37d54ffda58a1785fc593869ecf0656) changed the return values of **_zip_filetime_to_time_t**. The corresponding return value check should be changed too.

Fix check of _zip_filetime_to_time_t

---

lib/zip_random_uwp.c

- Simplify logic using the BCRYPT_SUCCESS macro, included in <bcrypt.h>
- Remove unused include <ntstatus.h>
- Put <windows.h> before <bcrypt.h> to fix compilation issues (some projects like [flycast ](https://github.com/flyinghead/flycast/blob/master/core/deps/libzip/lib/zip_random_uwp.c#L42-L43) or [ppsspp ](https://github.com/hrydgard/ppsspp/blob/d4d6dea443267878de1250b6365391f5502417c8/ext/libzip/zip_random_uwp.c#L43-L44)have done the same in order to build correctly, this change should help them to stay in sync with this repository)

zip_random_uwp: use BCRYPT_SUCCESS macro

---

CMakeLists.txt

This is for #311.
On Windows, zlib is usually named `zlib.lib` or `zlibd.lib`. Make `libzip.pc` contain the correct `-l` flag for this case.
On Unix platforms, `ZLIB_LIBRARIES` is usually something like `/path/to/libz.so` (or `.a`), which still results in `-lz` after this change.
When the CMake generator is Visual Studio (build type not known at config time), the result may not be correct for Debug builds. (This can only be fixed by generating the `.pc` at build type rather than configuration time.)
Tested on:
Windows, vcpkg zlib:x64-windows-static, Ninja, Debug (-> -lzlibd)
Windows, vcpkg zlib:x64-windows-static, Ninja, Release (-> -lzlib)
Windows, vcpkg zlib:x64-windows-static, Ninja, RelWithDebInfo (-> -lzlib)
Windows, vcpkg zlib:x64-windows-static, Visual Studio (-> -lzlib)
Windows, …

Better detect correct zlib flag in pkg-config file

---

cmake/FindMbedTLS.cmake

MbedTLS moved version string to `build_info.h`. MbedTLS 3 API wise should maintain compatibility - at least I did not notice any issue.

Support mbedtls3 discovery

---

lib/zip_error_strerror.c
lib/zip_source_file_stdio_named.c
regress/liboverride-test.c
src/diff_output.c
src/zipcmp.c

Notably, sprintf is deprecated when building agains the iOS16 or macOS13 SDKs

Replace usage of sprintf with snprintf

---

.github/workflows/build.yml
lib/zip.h
lib/zip_source_file_win32.h
lib/zip_source_file_win32_ansi.c
lib/zip_source_file_win32_named.c
lib/zip_source_file_win32_utf16.c

Clears up a bunch of warnings from building with clang-cl
Also adds a clang-cl build to GitHub Actions
I cleared the warnings for casting `something(*)(char*,...)` and `something(*)(wchar_t*,...)` functions to `something(*)(void*,...)` by disabling the warning.  Alternatives include explicitly doing casts or adding wrapper functions that take `void*`.  Preferences?

Clear up warnings when using clang-cl

---

lib/zip_source_buffer.c

Should fix an error on appveyor:
```
C:\projects\libzip\lib\zip_source_buffer.c(624): error C2064: term does not evaluate to a function taking 337 arguments [C:\projects\libzip\build\lib\zip.vcxproj]
C:\projects\libzip\lib\zip_source_buffer.c(624): error C2143: syntax error: missing ')' before 'type' [C:\projects\libzip\build\lib\zip.vcxproj]
C:\projects\libzip\lib\zip_source_buffer.c(624): error C2059: syntax error: ')' [C:\projects\libzip\build\lib\zip.vcxproj]
```

Fix windows build

---

lib/zip_fopen_index_encrypted.c
lib/zipint.h

Looking into the source/reference split and noticed an unused member.

Drop unused member.

---

CMakeLists.txt
libzip-config.cmake.in

This is required when building libzip as a static library.

Resolve optional transitive dependencies in libzip-config.cmake.

---

lib/zip_crypto_mbedtls.c

In recent Mbed-TLS versions >= 3.3.0, `mbedtls_pkcs5_pbkdf2_hmac` has been deprecated in favor of `mbedtls_pkcs5_pbkdf2_hmac_ext`:
* [890e78ae664363aace49449eec7e1f0fd5245925](https://github.com/Mbed-TLS/mbedtls/commit/890e78ae664363aace49449eec7e1f0fd5245925)
* [3d0dfb99c93f26539df4a6f43cfddf2f38dffd4f](https://github.com/Mbed-TLS/mbedtls/commit/3d0dfb99c93f26539df4a6f43cfddf2f38dffd4f)
This patch tries to make it seamless.
Cf openvehicles/libzip#1

deprecated function in Mbed-TLS 3.3.0+

---

CMakeLists.txt

This fixes the following warning when configuring with CMake 3.27+:
```
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
```

cmake: bump minimum required to version 3.5.0

---

lib/CMakeLists.txt
lib/zip_crypto_win.c

There are other files where windows.h is included but WIN32_LEAN_AND_MEAN is not defined. With this PR, WIN32_LEAN_AND_MEAN is defined consistently across the project

Define WIN32_LEAN_AND_MEAN to build the zip library on Windows

---

.github/workflows/codeql-analysis.yml

Fix warnings:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: github/codeql-action/init@v2, github/codeql-action/autobuild@v2, github/codeql-action/analyze@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
> CodeQL Action v2 will be deprecated on December 5th, 2024. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
https://github.com/nih-at/libzip/actions/runs/9300936029

Update github/codeql-action versions

---

lib/zip_source_file_win32_ansi.c
lib/zip_source_file_win32_utf16.c

When building with GCC14 to MinGW, the build currently fails due to multiple initializations of incompatible pointer types such as
```
/builddir/build/BUILD/mingw-libzip-1.10.1-build/libzip-1.10.1/lib/zip_source_file_win32_utf16.c:46:5: error: initialization of 'void * (__attribute__((stdcall)) *)(const void *, DWORD,  DWORD,  struct _SECURITY_ATTRIBUTES *, DWORD,  DWORD,  void *)' {aka 'void * (__attribute__((stdcall)) *)(const void *, long unsigned int,  long unsigned int,  struct _SECURITY_ATTRIBUTES *, long unsigned int,  long unsigned int,  void *)'} from incompatible pointer type 'void * (__attribute__((stdcall)) *)(const char *, DWORD,  DWORD,  struct _SECURITY_ATTRIBUTES *, DWORD,  DWORD,  void *)' {aka 'void * (__attribute__((stdcall)) *)(const char *, long unsigned int,  long …
```

Fix multiple initializations from incompatible pointer types

---

appveyor.yml

vcpkg in manifest mode creates the vcpkg_installed directory in the build directory
Amend commit https://github.com/nih-at/libzip/commit/d0ab65517578f7548380aa61d3aef9065f9927cd
CMake configure step exposed the vcpkg_installed directory in appveyor logs:
-- Found ZLIB: optimized;C:/projects/libzip/**build/vcpkg_installed**/x64-windows/lib/zlib.lib;debug;C:/projects/libzip/**build/vcpkg_installed**/x64-windows/debug/lib/zlibd.lib (found suitable version "1.3.1", minimum required is "1.1.2")

Fix appveyor vcpkg cache directory

---

lib/zip_source_file_win32.h
lib/zip_source_file_win32_ansi.c
lib/zip_source_file_win32_named.c
lib/zip_source_file_win32_utf16.c

Data-deduplicated files should be treated as regular files since this feature is designed to be transparent to the filesystem client.  It requires an additional check on the reparse point tag after file attributes reveals it uses a reparse point. 
Fixes #449

Fix zip_open failure with data-deduplicated file (Windows)

---

cmake/FindNettle.cmake

Gentoo Linux rewrites /usr/include/nettle/version.h to support multiple ABIs.
Even with Nettle 3.10 installed this results in:
-- Could NOT find Nettle: Found unsuitable version ".", but required is at least "3.0" (found /usr/lib64/libnettle.so)
---
I tried to otherwise maintain the logic; there might be other choices depending on when `set(Nettle_VERSION "1.0")` is wanted.

FindNettle: Prefer pkg-config Nettle version

---

lib/zip_file_set_encryption.c

If password is set twice, the first allocation is never freed
Reported as https://github.com/php/php-src/issues/19932
PHP use as workaround to free the first password:
zip_file_set_encryption(intern, index, ZIP_EM_NONE, NULL)

Fix memory leak on multiple call to zip_file_set_encryption
